# Basic
title: aochong
subtitle:
welcome_message: <a href="https://github.com/sparkaochong" target="_blank"></a>
description: 敖翀的个人技术博客
creator: <a href="http://onev.cat">@onevcat</a>

url: "https://sparkaochong.github.io/aochong.github.io/"

permalink: /:year/:month/:title/

# Format
highlighter: rouge
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", tables]

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color:

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    # - {title: Projects, description: My Projects, url: 'http://project.onevcat.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: aochong
    duoshuo: aochong
    
# Social
social:
    weibo: aochongi
    github: sparkaochong
    twitter: 
    gplus: 
    mail: sparkaochong@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
